### PR TITLE
Expand groups in JIRA API calls

### PR DESCRIPTION
**Pull request by j-matus**
Add ?expand=groups query string to JIRA API calls to ensure the groups
are included in SSO API responses. The group list can be used to
determine the user's rights in an application integrated with SSO.

### CODE REVIEW

**Comment by domiin50** [comment]
This parameter is needed when calling _myself_ API. What about the other JIRA proxy requests? It is not always needed to use _expand_ query param, isn't it?

**Comment by hleumas** [comment]
Agreed with @domiin50

**Comment by domiin50** [comment]
Handling of all query params is fixed in #9. Now when calling _myself_ API from an app connected to SSO, the _expand_ query param (or whatever) should be present in the request.
@michal-lenik, is it sufficient for your use case?

**Comment by michal-lenik** [comment]
@j-matus Is @domiin50 's solution good enough?

**Comment by michal-lenik** [comment]
I suppose this is no longer needed because of #9

**Pull request closed without merging**
