### PR TITLE
Fix using domain from config on EMS requests

### PR DESCRIPTION
**Pull request by domiin50**

### CODE REVIEW

**Comment by hleumas** [comment]
You still haven't explained WHY do you make this change in the commit message. And frankly, I myself don't understand your motivations.

**Comment by domiin50** [comment]
> You still haven't explained WHY do you make this change in the commit message. And frankly, I myself don't understand your motivations.

We have various deployments of the EMS. I use a different domain of EMS in development than in production. So I think it is wanted to be able to set the url from config and not to be hardcoded, isn't it?

**Comment by michal-lenik** [comment]
For clarification, Dominik has setup VLSSO locally in order to integrate it with Finetracker because he didn't have production VLSSO key which is needed if he wanted to use remote production VLSSO. (and he needed to contribute to its repo anyway) Because VLSSO runs locally, he needs to have api key to EMS in env and only stage EMS api key is available for that purpose. And that's why he has to change EMS url to stage server

**Comment by hleumas** [comment]
Good. That's reasonable explanation and this is how it should have been explained in the commit message:

https://github.com/vacuumlabs/vlsso/commit/0edf9447b565b8dd56415fb93bfc439077aa3a95

**Pull request merged**
